{application, epop,
 [{description, "Erlang POP3 client/server"},
  {vsn, "1.1"},
  {modules, [epop,
             epop_biff,
             epop_client,
             epop_db,
             epop_dbg,
             epop_dets,
             epop_inc,
             epop_md5,
             epop_notify,
             epop_server,
             epop_smtp_client, 
             epop_test]},
  {registered, []},
  {applications, [kernel, 
                  stdlib, 
                  sasl]}
]}.
